# Generated by Django 5.1.2 on 2026-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_add_ai_chatbot_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('sprint', 'Sprint'), ('speaking', 'Speaking'), ('consultancy', 'Consultancy'), ('special', 'Special'), ('positive_psychology', 'Positive Psychology'), ('nlp', 'NLP'), ('nutrition', 'Nutrition'), ('naturopathy', 'Naturopathy'), ('hypnotherapy', 'Hypnotherapy'), ('ayurveda', 'Ayurveda'), ('art_therapy', 'Art Therapy'), ('aroma_therapy', 'Aroma Therapy')], default='sprint', max_length=20),
        ),
    ]
