# Generated by Django 5.1.2 on 2026-02-16 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_course_course_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, GBP)', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether this course requires payment'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='purchase_id',
            field=models.CharField(blank=True, help_text='External purchase ID (legacy)', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Purchase amount', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, help_text="Payment provider (e.g., 'stripe', 'paypal', 'manual')", max_length=50)),
                ('provider_id', models.CharField(blank=True, help_text='Provider transaction/payment ID', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was confirmed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or metadata')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='myApp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='course_purchase',
            field=models.ForeignKey(blank=True, help_text='Source course purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to='myApp.coursepurchase'),
        ),
        migrations.AddIndex(
            model_name='coursepurchase',
            index=models.Index(fields=['user', 'course', 'status'], name='myApp_cours_user_id_c3e46f_idx'),
        ),
        migrations.AddIndex(
            model_name='coursepurchase',
            index=models.Index(fields=['status', 'paid_at'], name='myApp_cours_status_503816_idx'),
        ),
        migrations.AddIndex(
            model_name='coursepurchase',
            index=models.Index(fields=['provider', 'provider_id'], name='myApp_cours_provide_1c600c_idx'),
        ),
    ]
