# Generated by Django 5.1.2 on 2026-02-16 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_course_currency_course_is_paid_course_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Teachers assigned to this course', related_name='taught_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Session title (e.g., 'Week 1 Live Q&A')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Session description or agenda')),
                ('scheduled_at', models.DateTimeField(help_text='When the session is scheduled')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Session duration in minutes')),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Google Meet/etc. link')),
                ('meeting_password', models.CharField(blank=True, help_text='Meeting password if required', max_length=100)),
                ('capacity', models.IntegerField(blank=True, help_text='Maximum number of attendees (null = unlimited)', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for teacher')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='myApp.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('attended', models.BooleanField(default=False, help_text='Marked as attended by teacher')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_marked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Teacher notes about this booking')),
                ('attendance_marked_by', models.ForeignKey(blank=True, help_text='Teacher who marked attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myApp.livesession')),
            ],
            options={
                'ordering': ['booked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['course', 'status', 'scheduled_at'], name='myApp_lives_course__e3d378_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['status', 'scheduled_at'], name='myApp_lives_status_886f71_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'session'], name='myApp_booki_user_id_9b09f0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['session', 'status'], name='myApp_booki_session_d971d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'session')},
        ),
    ]
