# Generated by Django 5.1.2 on 2026-02-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_course_teachers_livesession_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='delivery_type',
            field=models.CharField(
                choices=[('pre_recorded', 'Pre-Recorded'), ('live', 'Live Course')],
                default='pre_recorded',
                help_text='How the course is delivered',
                max_length=20
            ),
        ),
    ]

