# Generated by Django 5.1.2 on 2026-02-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_add_course_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_video_url',
            field=models.URLField(blank=True, help_text='Optional preview/promo video URL (YouTube, Vimeo, etc.)'),
        ),
    ]

