# Generated by Django 5.1.2 on 2026-02-17 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_add_course_preview_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text='Email address of the gift recipient', max_length=254)),
                ('recipient_name', models.CharField(blank=True, help_text='Name of the gift recipient', max_length=200)),
                ('gift_message', models.TextField(blank=True, help_text='Optional message from the purchaser')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gift_token', models.CharField(help_text='Unique token for gift redemption', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When gift email was sent', null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, help_text='When gift was redeemed', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Gift expiration date (optional)', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_purchases', to='myApp.course')),
                ('course_purchase', models.OneToOneField(blank=True, help_text='Linked purchase record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_purchase', to='myApp.coursepurchase')),
                ('purchaser', models.ForeignKey(help_text='User who purchased the gift', on_delete=django.db.models.deletion.CASCADE, related_name='gift_purchases', to=settings.AUTH_USER_MODEL)),
                ('recipient_user', models.ForeignKey(blank=True, help_text='User who redeemed the gift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='giftpurchase',
            index=models.Index(fields=['gift_token'], name='myApp_giftp_gift_to_abc123_idx'),
        ),
        migrations.AddIndex(
            model_name='giftpurchase',
            index=models.Index(fields=['recipient_email', 'status'], name='myApp_giftp_recipie_def456_idx'),
        ),
        migrations.AddIndex(
            model_name='giftpurchase',
            index=models.Index(fields=['status', 'expires_at'], name='myApp_giftp_status_ghi789_idx'),
        ),
    ]

