# Generated by Django 5.1.2 on 2026-02-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_add_gift_purchase'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='giftpurchase',
            new_name='myApp_giftp_gift_to_1b5546_idx',
            old_name='myApp_giftp_gift_to_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='giftpurchase',
            new_name='myApp_giftp_recipie_7516ad_idx',
            old_name='myApp_giftp_recipie_def456_idx',
        ),
        migrations.RenameIndex(
            model_name='giftpurchase',
            new_name='myApp_giftp_status_7efa9a_idx',
            old_name='myApp_giftp_status_ghi789_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('sprint', 'Sprint'), ('speaking', 'Speaking'), ('consultancy', 'Consultancy'), ('special', 'Special'), ('positive_psychology', 'Positive Psychology'), ('nlp', 'NLP'), ('nutrition', 'Nutrition'), ('naturopathy', 'Naturopathy'), ('hypnotherapy', 'Hypnotherapy'), ('ayurveda', 'Ayurveda'), ('art_therapy', 'Art Therapy'), ('aroma_therapy', 'Aroma Therapy'), ('tawjehi', 'Tawjehi')], default='sprint', max_length=20),
        ),
    ]
