# Generated by Django 5.1.2 on 2026-02-17 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_rename_myapp_giftp_gift_to_abc123_idx_myapp_giftp_gift_to_1b5546_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('enrolled', 'Enrolled'), ('converted', 'Converted'), ('lost', 'Lost'), ('nurturing', 'Nurturing')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('email_campaign', 'Email Campaign'), ('paid_ads', 'Paid Ads'), ('organic_search', 'Organic Search'), ('webinar', 'Webinar'), ('event', 'Event'), ('other', 'Other')], db_index=True, default='website', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the lead')),
                ('last_contact_date', models.DateTimeField(blank=True, help_text='Last time lead was contacted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('linked_user', models.OneToOneField(blank=True, help_text='Linked user account if lead has registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_profile', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Assigned CRM owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadEnrollmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_links', to='myApp.courseenrollment')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_links', to='myApp.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadGiftLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_links', to='myApp.giftpurchase')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_links', to='myApp.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('LEAD_STATUS_CHANGED', 'Status Changed'), ('LEAD_OWNER_CHANGED', 'Owner Changed'), ('LEAD_NOTE_ADDED', 'Note Added'), ('USER_LINKED_TO_LEAD', 'User Linked'), ('USER_UNLINKED_FROM_LEAD', 'User Unlinked'), ('GIFT_LINKED_TO_LEAD', 'Gift Linked'), ('GIFT_UNLINKED_FROM_LEAD', 'Gift Unlinked'), ('ENROLLMENT_LINKED_TO_LEAD', 'Enrollment Linked'), ('ENROLLMENT_UNLINKED_FROM_LEAD', 'Enrollment Unlinked'), ('ENROLLMENT_CREATED', 'Enrollment Created')], max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the event')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', related_query_name='timeline', to='myApp.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'source'], name='myApp_lead_status_1d987a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='myApp_lead_email_e18cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner', 'status'], name='myApp_lead_owner_i_1a9134_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadenrollmentlink',
            unique_together={('lead', 'enrollment')},
        ),
        migrations.AlterUniqueTogether(
            name='leadgiftlink',
            unique_together={('lead', 'gift')},
        ),
        migrations.AddIndex(
            model_name='leadtimeline',
            index=models.Index(fields=['lead', '-created_at'], name='myApp_leadt_lead_id_ed4d33_idx'),
        ),
    ]
