# Generated by Django 5.1.2 on 2026-02-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_teacherrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teacherrequest',
            new_name='myApp_teach_status_c05034_idx',
            old_name='myApp_teach_status_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherrequest',
            new_name='myApp_teach_created_1a8100_idx',
            old_name='myApp_teach_created_idx',
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.FileField(blank=True, help_text='Upload a PDF template for certificates. Use placeholders: {student_name}, {course_name}, {date}, {certificate_id}', null=True, upload_to='certificate_templates/'),
        ),
    ]
