# Generated by Django 5.1.2 on 2026-02-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_rename_myapp_teach_status_idx_myapp_teach_status_c05034_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_field_positions',
            field=models.JSONField(blank=True, help_text="JSON object storing field positions for certificate template: {'student_name': {'x': 100, 'y': 200}, ...}", null=True),
        ),
    ]

