# Generated by Django 4.2.29 on 2026-03-29 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0025_make_preview_video_url_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('headline', models.CharField(blank=True, help_text='Short professional headline', max_length=160)),
                ('bio', models.TextField(blank=True, help_text='Public biography shown to students')),
                ('accomplishments', models.TextField(blank=True, help_text='One accomplishment per line (displayed as bullet points)')),
                ('website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name', 'user__username'],
            },
        ),
    ]
