# Generated by Django 4.2.29 on 2026-03-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='photo_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for cleanup', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='photo',
            field=models.URLField(blank=True, help_text='Cloudinary secure URL for teacher profile image', null=True),
        ),
    ]
