# Generated by Django 5.1.2 on 2026-05-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_course_v3_landing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('sprint', 'Sprint'), ('speaking', 'Speaking'), ('consultancy', 'Consultancy'), ('special', 'Special'), ('tawjehi', 'Tawjehi')], default='sprint', max_length=20),
        ),
    ]
